version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: ./packages/jse-backend/
      dockerfile: Dockerfile # on move to prod, update this
    environment:
      - PGHOST=ep-green-block-875072.us-east-2.aws.neon.tech
      - PGDATABASE=neondb
      - PGUSER=sayyidmuhammada
      - PGPASSWORD=KaABOCjbn29L
      - ENDPOINT_ID=ep-green-block-875072
      - USE_DOCKER=false
    volumes:
      - ./packages/jse-backend:/jse-backend
    ports:
      - 8080:8080
    restart: unless-stopped
  frontend:
    container_name: frontend
    build:
      context: ./packages/jse-frontend/
      dockerfile: Dockerfile # on move to prod, update this
    volumes:
      - ./packages/jse-frontend:/jse-frontend
    ports:
      - 3000:3000
    restart: always
