name: Deploy backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/jse-backend/
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm build
      - name: Install Railway
        run: npm i -g @railway/cli
      - name: Deploy the backend
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
